---
language: ruby
bundler_args: --without development
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.7
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="no"
  - rvm: 2.3.7
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="no"
sudo: false
